version: "3"
services:
   api:
    build: .
    container_name: fastapi
    command: ["python", "-m", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8888", "main:app"]
    volumes:
      - ./:/app/
    ports:
      - "8888:8888"

